using System;
using System.Collections.Generic;
using System.Text;

namespace DotNetVersions.Assets
{
    public static class SampleText
    {
        public static string Text = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut malesuada ullamcorper viverra. Curabitur quis leo vitae eros lacinia mattis. Praesent quis elit at felis varius ornare. In non venenatis odio. Cras hendrerit massa in nisi aliquet congue. Fusce malesuada sagittis sodales. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam suscipit nisi et sapien placerat, non ullamcorper tortor faucibus. Integer lobortis purus at felis ornare imperdiet. Phasellus iaculis egestas magna at luctus. Suspendisse potenti. Aenean et pharetra nisl.

Curabitur molestie lacinia ligula, eget vulputate nibh feugiat sit amet. Nunc sollicitudin nunc id ante malesuada, eget maximus purus commodo. Integer eleifend, ante ut tempus convallis, nunc nisi accumsan tortor, ultricies ullamcorper velit velit ut ex. Morbi accumsan tortor eros, in condimentum odio elementum at. Nulla nec elit viverra, bibendum arcu ultrices, semper sem. Proin iaculis, sapien nec elementum pellentesque, nulla dui dignissim mi, ut placerat nibh neque sed tortor. Aenean id luctus quam. Nulla diam velit, porttitor in condimentum eu, volutpat vitae tortor. Quisque eget ipsum maximus, commodo massa eu, tincidunt tellus. Nulla et mi pretium, mollis sapien eu, faucibus erat. In sed orci a neque varius dapibus nec at mauris. Mauris euismod lectus tellus, quis gravida neque venenatis ut.

Sed id lectus non metus vehicula porta. Quisque dui quam, semper eget eleifend quis, posuere in ligula. Praesent posuere eros vel leo aliquet, in consequat mi volutpat. Nunc laoreet rutrum justo, id viverra ipsum egestas ut. Integer in tempus dui. Sed sit amet sem condimentum, vestibulum est id, efficitur magna. Aliquam erat volutpat. Donec scelerisque pulvinar orci quis volutpat. Curabitur eu arcu augue. Duis at tortor mattis enim accumsan cursus. Sed varius, sapien ut sodales sagittis, tellus turpis condimentum risus, luctus congue dolor purus euismod massa. Mauris feugiat mattis purus sed malesuada. Morbi pellentesque ultrices risus, et luctus ex pretium ut. Aenean sapien sapien, lacinia a ligula vitae, cursus varius velit.

Sed leo urna, iaculis eu tincidunt at, elementum sit amet felis. Donec egestas, velit sit amet euismod ornare, odio felis congue leo, eget viverra tortor lorem a risus. Donec diam tortor, commodo rhoncus lectus sit amet, varius consequat nulla. Mauris dolor odio, suscipit nec libero a, mattis dictum lorem. Praesent auctor sapien a ipsum pellentesque, in suscipit nunc ullamcorper. Vestibulum vitae ex a mauris pretium feugiat aliquam in neque. Nunc eget diam a neque mollis aliquet. Donec cursus lacus sapien, id dapibus risus imperdiet mollis. Sed hendrerit vulputate accumsan.

Vivamus ac orci porttitor, mattis erat quis, varius elit. Proin convallis sapien sed erat ultrices, eget pulvinar lacus ultricies. Nulla nibh purus, dignissim vel lectus ac, blandit consequat tortor. Nam efficitur eros vitae tortor egestas hendrerit. Nunc est nisl, maximus et enim nec, vestibulum feugiat orci. Nam accumsan libero ac mi posuere, at euismod magna blandit. Nulla ut elementum lacus, eget scelerisque urna. Vestibulum condimentum justo sed nulla volutpat, nec fermentum ipsum accumsan. Curabitur a consectetur neque.

Morbi facilisis, ante nec ullamcorper consequat, est lectus aliquam urna, nec aliquet lectus nibh vitae nisi. Vivamus venenatis urna eu lacus pharetra, at cursus enim lacinia. Aliquam posuere odio odio, non semper massa venenatis eu. Donec rhoncus pretium tempus. Fusce eget augue id massa pretium vestibulum quis ac nibh. Quisque pellentesque, est a congue egestas, quam nulla vehicula erat, vel fermentum nibh risus in libero. Morbi nec erat quam. Morbi dignissim ultrices augue id lobortis. In aliquet metus eros, non tincidunt erat maximus a. Cras urna elit, ultrices at maximus vel, semper non metus. Phasellus arcu lorem, scelerisque non ullamcorper vitae, laoreet in tortor. Donec lorem sem, lacinia sed nunc in, accumsan tempor diam. Aenean pretium ligula odio, in euismod justo tincidunt in.

Etiam id eros varius massa consectetur eleifend a convallis turpis. Cras a massa non nibh molestie blandit ac a enim. Proin vitae finibus metus. Suspendisse in fermentum magna. Nam maximus purus eget nisi hendrerit pretium. Nullam neque nibh, tempus id ligula eu, accumsan dapibus mi. In sed purus pellentesque, lacinia urna a, imperdiet felis. Pellentesque vitae arcu rutrum, venenatis risus ac, vulputate arcu. Vestibulum quis feugiat purus. Nullam bibendum sapien turpis, id convallis nibh feugiat eu. Nunc porttitor ante sed velit efficitur, nec ornare lectus tristique. Donec vitae libero rutrum, ultricies lectus vitae, tempor nisi.

Nullam non scelerisque eros, venenatis cursus massa. In vel enim vel metus aliquet sollicitudin ut quis nunc. Phasellus id velit tincidunt, interdum nisi ut, pellentesque purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean eget ultricies velit. Nam hendrerit sollicitudin arcu, ac sagittis orci lacinia sit amet. Curabitur vel feugiat dui, non finibus massa. Fusce orci odio, pretium nec lorem convallis, elementum rutrum justo. Duis convallis porta lacus, posuere accumsan tellus egestas et. Maecenas pulvinar tellus in pulvinar hendrerit. Quisque justo enim, laoreet quis risus a, volutpat vestibulum magna. Aenean pulvinar sem pharetra erat vulputate, eget gravida quam condimentum.

Suspendisse malesuada finibus odio porttitor pretium. Curabitur euismod justo nec nisi placerat cursus. Vestibulum a commodo lorem. Cras pellentesque ipsum et tempor dictum. Curabitur ut placerat sapien. Quisque ac sapien lorem. Aenean sit amet pharetra augue, id viverra urna. Nullam finibus viverra dictum. Mauris congue id augue sit amet ornare. Proin ligula turpis, interdum id gravida vel, euismod a arcu. In hac habitasse platea dictumst. Ut gravida dui id diam scelerisque, sit amet sollicitudin eros congue. Nullam eget scelerisque velit. Proin fermentum sed ante at gravida. Sed sit amet ipsum non sem eleifend vulputate.

Aenean ornare lorem a dolor sodales, eget interdum felis congue. Cras non dui nulla. Etiam tortor augue, ultrices et arcu sed, euismod tincidunt arcu. Sed iaculis nec turpis sit amet bibendum. Vivamus rhoncus, turpis ultricies tempus commodo, dolor dolor lobortis lacus, vehicula placerat mi lacus vitae dolor. Suspendisse gravida at magna in sodales. Nam ornare pellentesque mi a congue. Curabitur aliquam mi non purus pharetra volutpat ut nec metus. Donec eleifend faucibus turpis. In hac habitasse platea dictumst. Ut maximus erat non justo fringilla, sed malesuada ligula faucibus. Vestibulum nec massa eu erat consequat maximus at nec urna. Phasellus egestas libero lectus, sed cursus quam fringilla eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et ultricies ex.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce cursus orci diam, eu malesuada elit scelerisque sit amet. Praesent mollis est arcu, quis porta sapien commodo a. Pellentesque commodo malesuada enim, vel fermentum justo dapibus et. Praesent sit amet volutpat quam. Cras a vehicula arcu. Etiam porttitor elementum nulla eget ultrices. Aliquam mollis tincidunt metus at dictum. Praesent at sem vestibulum, sagittis tellus a, eleifend dolor. Phasellus non arcu at ipsum malesuada rhoncus. Aenean sed lacus at sem tristique consectetur. Aenean in ullamcorper ante, eget mattis leo.

In sodales malesuada rhoncus. Ut viverra vulputate malesuada. Nam quis felis enim. Nam sapien nisl, cursus at rutrum et, efficitur sit amet nisl. In lobortis tellus vitae dolor sodales convallis. In ac mollis metus, at efficitur ex. Sed ut leo lacinia, interdum dolor rhoncus, pellentesque ante. Donec semper efficitur pretium. Duis malesuada consequat luctus. Nam et dui dui. Proin a aliquam nibh. Aenean orci lacus, cursus a lacinia id, consequat nec nisi. Quisque tincidunt ultrices cursus. Vestibulum id odio sed urna porttitor tempor non vitae magna.

Sed scelerisque feugiat augue, ac bibendum enim varius ut. Praesent in turpis efficitur, gravida urna et, tempor quam. Vestibulum velit tellus, consectetur eu ultrices nec, porttitor ut elit. Donec at mauris vitae felis gravida pharetra. Cras vestibulum sit amet nisi et egestas. In laoreet commodo congue. Proin convallis justo vitae arcu ullamcorper, in ultrices odio tempus. Nulla tempus dictum metus, vitae sodales est accumsan ut. In in dolor urna. Nulla et quam auctor, maximus ante vitae, efficitur magna. Ut viverra tellus et sagittis rhoncus. Nunc vitae nisl a mauris volutpat egestas. Fusce nec dolor eget diam interdum sollicitudin. Nam dapibus orci vitae luctus congue. In pellentesque massa nisl, ac mattis leo imperdiet eu. Pellentesque eget lectus quis lectus dapibus aliquam at at sem.

Mauris tempus ultricies lectus, a porttitor ex fringilla eget. Cras euismod dignissim nisl, ac mollis mauris tempor eu. Duis vehicula scelerisque tristique. Etiam a urna quam. Sed eget erat tortor. Ut vel ligula felis. Nullam id ligula nec dolor bibendum mollis. Nulla cursus ante eu massa semper dictum. Duis ultricies leo a tempor auctor. Pellentesque lacinia luctus imperdiet. Morbi sem magna, fringilla id sem ac, condimentum mattis enim. Mauris urna tellus, porta suscipit nulla ut, hendrerit scelerisque lectus. Morbi finibus erat in volutpat pharetra. Maecenas dictum enim ut est efficitur tristique. Ut pellentesque ullamcorper mi, eu semper enim lobortis et.

Cras placerat sem nec volutpat volutpat. Nunc a semper tellus. Aenean ornare eget urna a lacinia. Nunc ac orci a erat consectetur vulputate ac sit amet urna. Ut pharetra facilisis diam, quis placerat lectus egestas a. Vestibulum iaculis nunc vitae pretium pulvinar. Cras fringilla luctus quam, sit amet consequat sapien porttitor vel. Cras nec venenatis est, vel rhoncus odio. Sed cursus, sem sed consectetur commodo, lorem felis tempus lacus, aliquet efficitur leo nisi quis est.

Aliquam quis arcu ipsum. Curabitur lectus odio, ornare vitae varius ut, mattis at ipsum. Quisque venenatis tristique metus, quis tempor nunc iaculis a. Sed urna risus, auctor vel justo eget, finibus dignissim enim. Quisque congue enim aliquam, aliquet nibh ac, sodales augue. Aliquam congue fringilla velit sit amet consectetur. Pellentesque tincidunt dui id maximus imperdiet.

Cras mollis sit amet massa at tincidunt. Pellentesque sed dignissim odio, in dictum lectus. Etiam hendrerit purus sit amet dui interdum, et feugiat sapien condimentum. Proin lacinia odio ex, at bibendum elit ultrices at. Nullam hendrerit elementum ante, ut viverra risus gravida nec. Ut dictum bibendum metus, eget maximus nisl commodo sit amet. Nulla nec dolor nunc. Sed non sem non dolor rutrum lacinia eu luctus nulla. Integer eu tincidunt leo. Curabitur dapibus dui et elit pellentesque, ut vestibulum tellus posuere. Donec luctus aliquam convallis. Nullam id convallis arcu. Nulla urna ligula, tempor eu malesuada vel, sollicitudin vel ipsum.

Vivamus ac lacinia massa. Ut luctus scelerisque tincidunt. Integer scelerisque justo eu dignissim molestie. Maecenas lectus augue, sagittis non est a, pellentesque aliquam urna. Mauris sit amet lorem aliquam, feugiat lorem vel, fermentum leo. Pellentesque mi ligula, porttitor eu vestibulum a, mattis non purus. Suspendisse potenti. Quisque tempus, urna ac fringilla scelerisque, sem lectus egestas leo, id rutrum ante nisl et magna. Nunc ac commodo sem. Etiam egestas imperdiet interdum.

Curabitur non dolor ac ante placerat varius at at ipsum. Suspendisse consectetur dolor eu nulla placerat pulvinar. Nunc porta gravida massa, tempus mattis erat vestibulum ut. Morbi mollis dapibus lorem nec vehicula. Proin pulvinar luctus sem, id dictum nunc porttitor sit amet. Cras ut dolor quis enim eleifend ullamcorper. Cras placerat justo nisi, in mattis risus efficitur eget.

Sed id ipsum semper libero ullamcorper luctus eu eget tortor. Duis gravida lobortis elementum. Duis id pharetra risus. Vivamus molestie volutpat ante a efficitur. Maecenas porta mauris a tortor consectetur, ut porttitor sapien interdum. Nulla lacus ipsum, semper in tincidunt quis, finibus sed quam. Phasellus semper dui id lacus blandit, vitae vehicula dolor semper. In vitae eros porta, blandit ex et, malesuada dolor.

In finibus justo non erat lobortis mollis a ultricies sapien. Donec euismod malesuada nisi sit amet imperdiet. Integer nec mauris et massa imperdiet tincidunt. Praesent vitae enim nunc. Aenean lacinia scelerisque luctus. Curabitur in tellus elementum, tempus nibh nec, finibus metus. Integer non ullamcorper diam. Fusce vehicula nunc at massa blandit, sit amet sollicitudin enim venenatis.

Duis consectetur eros nec urna tristique molestie. In hac habitasse platea dictumst. Phasellus lorem eros, congue in ipsum a, venenatis aliquet tortor. Curabitur et pellentesque magna. Morbi pharetra neque eget dolor consectetur, eu tristique magna sodales. Morbi mauris mauris, maximus ut volutpat sed, dictum eu lacus. Mauris sed porta velit, eget ullamcorper arcu. Nam metus elit, luctus eget pellentesque at, pharetra gravida quam. Sed accumsan dui ac ipsum congue, eget imperdiet mauris tristique. Donec eu elit quis urna faucibus feugiat eu consectetur velit. Sed pellentesque sapien tellus, id rutrum turpis imperdiet fermentum. Aliquam sit amet bibendum orci. Ut at laoreet ligula. Sed quis mollis turpis. Duis ac sollicitudin nisi, eget dignissim nibh. Ut in molestie purus.

Pellentesque tristique fringilla lorem, et laoreet tortor dictum sit amet. Morbi vel sagittis nisl. Quisque at eros nisl. Nam nec posuere sapien. Suspendisse potenti. Curabitur justo velit, consequat vitae malesuada vel, pretium in nulla. In quis ornare nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse odio neque, facilisis ut magna non, tristique interdum nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Interdum et malesuada fames ac ante ipsum primis in faucibus.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam ut est a tortor porttitor viverra id sed libero. Mauris suscipit, metus in porttitor pharetra, ante eros euismod nunc, ac tincidunt elit turpis in turpis. Quisque at arcu et arcu varius imperdiet. Etiam id vehicula mauris, vel feugiat sapien. Vestibulum malesuada sit amet leo eget scelerisque. Curabitur tempor lectus eget nisi mattis convallis. Duis ornare lectus ipsum, sed molestie enim faucibus eget. Aenean at accumsan mauris. Donec arcu justo, pellentesque nec mi a, placerat fringilla dui. Phasellus eu vulputate nunc. Phasellus fringilla lacinia consectetur. Etiam velit libero, ullamcorper id nunc et, volutpat lobortis urna.

Nullam vulputate odio leo, tincidunt dapibus augue laoreet at. Sed lacinia facilisis magna. Morbi sit amet ligula sed velit posuere porta. Cras ultricies, nisl eget vestibulum luctus, ipsum libero consequat arcu, a tempor est metus sed lacus. In in erat placerat diam porta volutpat ut nec nunc. Quisque molestie gravida nisi, eu dignissim nibh tincidunt eu. Cras ac mollis ligula, volutpat tristique elit. Vestibulum convallis ipsum at ligula fringilla, non volutpat nisl euismod. Proin iaculis faucibus tellus, a scelerisque nibh sodales id. Integer iaculis leo quis nisi condimentum, non fermentum enim tincidunt. In fringilla vel lectus eget aliquam. Integer egestas ante sed magna accumsan dictum.

Suspendisse potenti. Vestibulum lobortis pulvinar libero ut luctus. Mauris quis nulla ac arcu maximus pulvinar. Duis ultricies tortor quis efficitur ultricies. Vestibulum ullamcorper malesuada tincidunt. Donec est mauris, sodales eu eleifend eget, semper a purus. Mauris libero nulla, venenatis sed aliquam eget, imperdiet a nunc. Nullam porta nisl ultrices arcu scelerisque, id volutpat nunc lobortis.

Sed nec erat ac purus fringilla ornare ullamcorper sit amet massa. Vivamus quis purus rhoncus ligula fermentum tempus ac eu tellus. Sed porta scelerisque sem ut tempor. Sed aliquet urna sit amet arcu porttitor, tincidunt volutpat metus pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non nibh eget sapien gravida viverra. Donec maximus mauris sit amet porta feugiat. In in egestas lectus.

Donec eget urna nec arcu placerat congue vitae non sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi porta tincidunt posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin mollis libero magna, eu tincidunt dolor varius id. Maecenas lobortis non nisl sit amet tristique. Maecenas porta et arcu sit amet commodo.

Suspendisse viverra suscipit ligula ornare semper. Ut et velit vel mauris posuere sagittis. Curabitur placerat at mauris eget iaculis. Integer nibh urna, consectetur vitae dapibus ac, bibendum non neque. Vestibulum cursus feugiat ullamcorper. Etiam faucibus ultrices tempus. Quisque aliquet blandit lacus id egestas. Donec velit lectus, hendrerit non viverra non, ultrices eget dui. Aenean fringilla non mauris sodales porttitor. Pellentesque ac porttitor augue, vitae pretium arcu. Aliquam malesuada auctor lacinia. Phasellus ac blandit mauris. Vestibulum scelerisque lorem eget viverra hendrerit. Suspendisse eleifend ultricies lorem, nec fringilla neque viverra vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sit amet luctus lorem.

Cras a tortor luctus, sagittis sem sed, sodales quam. Praesent dapibus felis sit amet elit tempor, vel malesuada erat tempor. Duis aliquet sit amet metus id bibendum. Nullam id felis blandit, eleifend ex et, convallis risus. Nunc ultrices convallis ante id consectetur. In hac habitasse platea dictumst. Morbi in turpis et neque ornare aliquam nec eu orci. Vestibulum ullamcorper odio tellus.";
    }
}
